Insert into fullpingdatabase.fullpingdata(addressid,ip,name,userid,username)
values (1,'10.67.134.23','PC_MASSIN',1,'Massin');

Insert into fullpingdatabase.fullpingdata(addressid,ip,name,userid,username)
values (2,'10.67.134.27','PC_IVAN',2,'Ivan');



Insert into fullpingusers.fullpingdatausers(userid,username,password)
values (1,'Massin','password1');

Insert into fullpingusers.fullpingdatausers(userid,username,password)
values (2,'Ivan','password2');